package org.lexicalAnalyzer;

public enum TokenType {
    IDENTIFIER,
    RESERVED_WORD,
    INTEGER,
    FLOATING_POINT,
    ARITHMETIC_OPERATOR,
    RELATIONAL_OPERATOR,
    LOGICAL_OPERATOR,
    ASSIGNMENT_OPERATOR,
    BITWISE_OPERATOR,
    GROUPING_CHARACTER,
    LITERAL_STRING,
    COMMENT,
    SPECIAL_CHARACTER,
    ERROR,
    EOF

}
